### ISSUE TITLE
Molecule folder not linted by molecule

### ISSUE THREAD

**Issue by christianhueserhzdr** [hifis-net/ansible-role-netplan#46]
When providing `.` as the folder path of the lintables to `ansible-lint` it does not lint the folder `molecule/default` containing `converge.yml`, `prepare.yml`, `verify.yml`, hence folder `molecule/` need to be added to the `ansible-lint` call in the `molecule lint` commands.

**Comment by tobiashuste** [comment]
This is fixed via #56
